steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/archive-playout:$COMMIT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/archive-playout:$COMMIT_SHA']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'archive-playout'
      - '--image'
      - 'gcr.io/$PROJECT_ID/archive-playout:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'APP_ENV=production,APP_DEBUG=false,APP_KEY=base64:$(openssl rand -base64 32),APP_URL=https://archive-playout-362374170433.us-central1.run.app,DB_CONNECTION=mysql,DB_HOST=/cloudsql/archive-playout-platform:us-central1:archive-playout-db,DB_PORT=3306,DB_DATABASE=archive_playout,DB_USERNAME=root,DB_PASSWORD=archive_Hq$2025,CACHE_DRIVER=file,QUEUE_CONNECTION=sync,SESSION_DRIVER=file'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:archive-playout-db'

images:
  - 'gcr.io/$PROJECT_ID/archive-playout:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY 